version: '3'
services:
  db:
    container_name: go-gin-db
    restart: always
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  api:
    container_name: go-gin-api
    build: .
    image: go-gin-api
    environment:
      PORT: 8080
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      AUTH_TOKEN: bork
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db